# Simple workflow for deploying static content to GitHub Pages
name: Deploy content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      purgeCache:
        description: "A list of URLs to purge from the cache, separated by \"|\".\n\nTo clear the entire cache, use \"--all\"."
        default: ""

      recheckUrls:
        description: "Should the existing URLs be re-checked to determine if there are any missing?"
        type: boolean
        default: false

  schedule:
    - cron: "48 0 * * *"

  repository_dispatch:
    types: [trigger_deploy]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get username and repository
        run: |
          echo "REPO_USERNAME=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "REPO_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Set pages url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          HOMEPAGE_URL="$(curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY" | jq -r '.homepage' | sed 's/\/$//')"
          if [ "$HOMEPAGE_URL" == "null" ]; then
            echo "PAGES_URL=https://$REPO_USERNAME.github.io/$REPO_NAME" >> $GITHUB_ENV
          else
            echo "PAGES_URL=$HOMEPAGE_URL" >> $GITHUB_ENV
          fi

      - name: Set page path
        run: |
          echo "PAGES_PATH=$(echo "$PAGES_URL" | awk -F/ -v OFS="/" '{$1=$2=$3=""; print $0}' | sed 's/\/\+/\//')" >> $GITHUB_ENV

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download cache
        if: (github.event.inputs.purgeCache != '--all')
        continue-on-error: true
        run: |
          wget "$PAGES_URL/cache.txz?`date +%s`" -O website/public/cache.txz

      - name: Extract cache
        if: (github.event.inputs.purgeCache != '--all')
        continue-on-error: true
        run: |
          tar -xJvf website/public/cache.txz

      - name: Delete cache
        if: (github.event.inputs.purgeCache != '--all')
        continue-on-error: true
        run: |
          rm website/public/cache.txz

      - name: Install npm modules
        run: |
          cd scripts
          npm install
          cd ../website
          npm install

      - name: Purge specified items from cache
        if: ((github.event.inputs.purgeCache != '') && (github.event.inputs.purgeCache != '--all'))
        run: |
          cd scripts
          npx tsx ./purgecache.ts "${{ github.event.inputs.purgeCache }}"

      - name: Process the json (schedule)
        if: (github.event_name == 'schedule' || github.event.inputs.recheckUrls == 'true')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd scripts
          npx tsx ./combine.ts "--baseHref=$PAGES_URL" --updateFunding --recheckUrls 2>&1 | tee ../website/public/deploy-log.txt

      - name: Process the json (normal)
        if: (github.event_name != 'schedule')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd scripts
          npx tsx ./combine.ts "--baseHref=$PAGES_URL" 2>&1 | tee ../website/public/deploy-log.txt

      - name: "Archive cache"
        run: |
          tar -cJvf website/public/cache.txz \
            website/public/covers \
            website/public/funding-info.json \
            website/public/mod-metadata.json

      - name: Build website
        run: |
          cd website
          npx astro build --base "$PAGES_PATH"

      - name: Precompress assets
        run: |
          find website/out -type f | while read -r file; do
            if [[ "$file" == *.html || "$file" == *.css || "$file" == *.js || "$file" == *.json ]]; then
              echo "$file"
              brotli -k -q 11 "$file"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./website/out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
