# Simple workflow for deploying static content to GitHub Pages
name: Update core mods

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Every 30 minutes
  schedule:
    - cron: "*/30 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update the core mods
        if: ${{ github.event_name == 'schedule' }}
        run: "cd scripts && npm install && npx tsx ./import.ts 2>&1"

      - name: Commit the updated files
        run: |
          git add -A mods
          git commit -m "Update core mods"
          git push
