# Simple workflow for deploying static content to GitHub Pages
name: Update mods from known repos

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "24 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow push and requesting PRs
permissions:
  pull-requests: write
  contents: write

jobs:
  # Single deploy job since we're just deploying
  update-mods:
    concurrency:
      group: update-mods-${{ github.ref }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm modules
        run: |
          (cd source/scripts && npm install)

      - name: Update the mods from known repos.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd source/scripts
          npx tsx ./update-mods.ts 2>&1

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make commits for the new mods.
        run: |
          cd source/scripts
          npx tsx ./commit-new-mods.ts 2>&1

      - name: Reset the repository working directory.
        run: |
          git reset --hard

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update Mods
          commit-message: Update mods
          branch: update-mods
